version: '3.8'

services:
  api:
    image: retail_api
    ports:
      - "8000:8000"
    networks:
      - mynetwork

  database:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: lg
      POSTGRES_PASSWORD: glop
      POSTGRES_DB: sales_db
    volumes:
      - postgres-data:/var/lib/postgresql/data 
    networks:
      - mynetwork
    restart: always

  script:
    image: etl:0.1
    depends_on:
      - api
      - database
    env_file:
      - prod.env
    volumes:
      - cron-logs:/var/log/cron
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge

volumes:
  postgres-data:
  cron-logs: